GET http://localhost:3000/pessoa
Accept: application/json

###
POST http://localhost:3000/pessoa
Content-Type: application/json

{"id": 1, "name": "Rafael"}

###
DELETE http://localhost:3000/pessoa/1
Accept: application/json